### ISSUE TITLE
Node become unresponsive during synchronization

### ISSUE THREAD

**Issue by LNow** [stacks-network/stacks-blockchain#2955]
I have almost fully synchronized node and suddenly it started to be unresponsive. It outputs `Atlas: X attachment instances emitted from events` msg and hangs without doing anything (for hours).
After restart it synchronize a little bit (few burnchain blocks tops) and again hangs on the same message

**Config file:**
```toml
[node]
working_dir = "/home/lnow/Projects/blockstack/follower"
rpc_bind = "0.0.0.0:22443"
p2p_bind = "0.0.0.0:22444"
bootstrap_node = "02da7a464ac770ae8337a343670778b93410f2f3fef6bea98dd1c3e9224459d36b@seed-0.mainnet.stacks.co:20444,02afeae522aab5f8c99a00ddf75fbcb4a641e052dd48836408d9cf437344b63516@seed-1.mainnet.stacks.co:20444,03652212ea76be0ed4cd83a25c06e57819993029a7b9999f7d63c36340b34a4e62@seed-2.mainnet.stacks.co:20444"

[[events_observer]]
endpoint = "localhost:3000"
retry_count = 255
events_keys = ["*"]

[burnchain]
chain = "bitcoin"
mode = "mainnet"
peer_host = "bitcoind.stacks.co"
username = "blockstack"
password = "blockstacksystem"
rpc_port = 8332
peer_port = 8333

[connection_options]
read_only_call_limit_write_length = 0
read_only_call_limit_read_length = 100000
read_only_call_limit_write_count = 0
read_only_call_limit_read_count = 30
read_only_call_limit_runtime = 1000000000
```

**Log file:** [log.log](https://github.com/blockstack/stacks-blockchain/files/7621061/log.log)
**Version:** 2.05.0.0.0
