### ISSUE TITLE
[Stacks 2.1] Epoch 2.0 boot data is not emitted to event-observers

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#3367]
The boot contracts (e.g. bns, pox, seed account balances, etc) are ignored / not emitted through the event-observer interface when bootstrapping a neon/krypton Stacks node to Epoch 2.1.

This _appears_ to be only a bug in the event-emitter code, because while boot contracts & balances are not emitted, they are still visible through RPC / `v2/<endpoint>` calls.

This behavior breaks event-observers like the API which end up with negative STX balances for config.toml seed accounts, missing contract ABIs for pox-1 and bns, etc..

Using something like the following to bootstrap a Stacks node into krypton mode (this is paired with a bitcoind instance booted into regtest mode and an regtest auto-mining script):

```toml
[node]
name = "krypton-node"
rpc_bind = "0.0.0.0:20443"
p2p_bind = "0.0.0.0:20444"
working_dir = "$DATA_DIR"

seed = "$MINER_SEED"
local_peer_seed = "$MINER_SEED"

miner = true
use_test_genesis_chainstate = true
pox_sync_sample_secs = 0
wait_time_for_microblocks = 50
microblock_frequency = 5000
# mine_microblocks = true
# max_microblocks = 10

[miner]
first_attempt_time_ms = 5000
subsequent_attempt_time_ms = 5000

[connection_options]
disable_block_download = true
disable_inbound_handshakes = true
disable_inbound_walks = true

[burnchain]
chain = "bitcoin"
mode = "krypton"
poll_time_secs = 1
pox_2_activation = 104 # note that this is based off starting with a regtest bitcoind node that mines 101 blocks for a BTC balance, where something like 104 is is stacks_block=1, 105 is stacks_block=2, etc.. this can also be set to a value lower than min bitcoin-regtest confirmation blocks, but will result in various burnblock_height values being extra buggy

### bitcoind-regtest connection info
peer_host = "$BITCOIN_PEER_HOST"
peer_port = "$BITCOIN_PEER_PORT"
rpc_port = "$BITCOIN_RPC_PORT"
rpc_ssl = false
username = "$BITCOIN_RPC_USER"
password = "$BITCOIN_RPC_PASS"
timeout = 30

[[burnchain.epochs]]
epoch_name = "1.0"
start_height = 0

[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 1

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 2

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 103 # note that this is based off starting with a regtest bitcoind node that mines 101 blocks for a BTC balance, where something like 104 is is stacks_block=1, 105 is stacks_block=2, etc.. this can also be set to a value lower than min bitcoin-regtest confirmation blocks, but will result in various burnblock_height values being extra buggy

[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000

[[ustx_balance]]
address = "ST11NJTTKGVT6D1HY4NJRVQWMQM7TVAR091EJ8P2Y"
amount = 10000000000000000
```

**Comment by zone117x** [comment]
> Can we specify which observer endpoints, and possibly even which fields, are affected?

Yes it's missing data from the genesis (first) `/new_block` event payload. In particular, the boot contracts (e.g. bns, pox, etc) no longer have their associated contract-deploy txs in the genesis block. Similarly, seed accounts no longer have stx-transfer events in the genesis block -- these are the ones that can be added to config.toml e.g.
```toml
[[ustx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 10000000000000000
```

**Comment by gregorycoppola** [comment]
I think I _am_ seeing the right events possibly. I'll upload the toml file and the log from my listener.
[epochs-output.zip](https://github.com/stacks-network/stacks-blockchain/files/9933021/epochs-output.zip)

**Comment by zone117x** [comment]
Thanks for the testing @gregorycoppola!

From comparing your config to mine, it looks like this is what probably makes the difference:
(your config)
```toml
[[burnchain.epochs]]
epoch_name = "2.0"
start_height = 105

[[burnchain.epochs]]
epoch_name = "2.05"
start_height = 106

[[burnchain.epochs]]
epoch_name = "2.1"
start_height = 107
```

The <2.1 epochs are each configured to mine at least 1 stacks block (if perfectly in sync with the burnchain block height). My config has those set to the minimum possible values taken from the original PR where this config was introduced, which allows booting into an epoch 2.1 Stacks node ASAP. I'll look into adjust the regtest env setup and API to use this config and verify the results. 

We should consider fixing/implementing a "fast epoch2.1" config to avoid this issue, because while it's useful to test the epoch transitions right now, as soon as 2.1 launches, this extra ceremony will just become a developer burden.
