### ISSUE TITLE
[Stacks 2.1] Regtest+Krypton miner does not produce blocks with empty mempool

### ISSUE THREAD

**Issue by zone117x** [stacks-network/stacks-blockchain#3404]
@lgalabru and I both ran into what appears to be a regression with regtest+krypton mining. 

When the mempool is empty, the miner stalls rather than mining empty blocks. This behavior seems to have been introduced from the last merge from `master` into `next` a couple weeks ago.

A workaround for this is to add the following to config.toml:
```toml
[node]
wait_time_for_blocks = 0 # fixes stalled miner
```

Unclear to me if this is intended new behavior or a bug.
