### ISSUE TITLE
Update core contract tests to use the Clarinet SDK

### ISSUE THREAD

**Issue by wileyj** [stacks-network/stacks-blockchain#4030]
With the recent changes outlined here: https://www.hiro.so/blog/announcing-the-clarinet-sdk-a-javascript-programming-model-for-easy-smart-contract-testing

The core contract tests should be updated to use this SDK rather than relying on a soon to be outdated docker image. 
Currently, the only test being run is for the `bns.clar` contract using this step:
```yml
      - name: Execute core contract unit tests in Clarinet
        id: clarinet_unit_test
        uses: docker://hirosystems/clarinet:1.1.0
        with:
          args: test --coverage --manifest-path=./contrib/core-contract-tests/Clarinet.toml
 ```
ref: https://github.com/stacks-network/stacks-blockchain/blob/master/contrib/core-contract-tests/Clarinet.toml#L9

Future work should also be done to include other active boot contracts like `pox-3.clar` 
https://github.com/stacks-network/stacks-blockchain/tree/master/src/chainstate/stacks/boot

tagging @hugocaillard
